site_name: Easy Translate
site_url: https://easy-translate.example.com # will change later
theme:
  name: material
  logo: assets/enlpt_logo.png
  favicon: assets/enlpt_logo.png
  palette:
    # darkmode 
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Dark mode
      primary: blue
      accent: deep-purple
    # lightmode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Light mode
      primary: blue
      accent: deep-purple
  language: en
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - search.highlight
    - content.code.annotate

nav:
  - Home: index.md
  - Docs:
    - Overview: package_docs/overview.md
    - Non-LLM Translation: package_docs/non_llm_translation.md
    - LLM Translation: package_docs/llm_translation.md
  - Evaluation:
    - Overview: evaluation/overview.md
    - Metrics: evaluation/metrics.md
    #- Evaluator: evaluation/evaluator.md
    #- Models: evaluation/model.md
    #- Config: evaluation/config.md
    #- Usage: evaluation/usage.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_root_full_path: false
            show_source: false
            preload_modules:
            - src.translator_base
            - src.huggingface_translator_base

# emoji support
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
