site_name: Easy Translate
site_url: https://easy-nlp-translate.de
repo_url: https://github.com/olefSch/easy_translate
theme:
  name: material
  logo: assets/enlpt_logo.png
  favicon: assets/enlpt_logo.png
  palette:
    # darkmode 
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Dark mode
      primary: blue
      accent: deep-purple
    # lightmode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Light mode
      primary: blue
      accent: deep-purple
  language: en
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - content.code.annotate

nav:
  - Home: index.md
  - Docs:
    - Overview: package_docs/overview.md
    - Non-LLM Translation: package_docs/non_llm_translation.md
    - LLM Translation: package_docs/llm_translation.md
    - Language Support: package_docs/languages_support.md
  - Evaluation:
    - Overview: evaluation/overview.md
    - Metrics: evaluation/metrics.md
    - Own Usage:
      - Usage: evaluation/usage.md
      - Config: evaluation/config.md
      - Evaluator: evaluation/evaluator.md
      - Models: evaluation/model.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_inherited_members: true
            inherited_members: true
            show_bases: false
            show_source: true
            show_root_heading: true
            show_root_full_path: false
            show_source: false

# emoji support
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences 
  - pymdownx.details    
  - admonition  
