[project]
name = "easy-translate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.29.5",
]

[dependency-groups]
dev = [
    "pyright[nodejs]>=1.1.398",
    "pytest>=8.3.5",
]
[tool.pytest.ini_options]
pythonpath = "src"
