site_name: Easy Translate Evaluation
site_url: https://olefsch.github.io/easy_translate/
repo_url: https://github.com/olefSch/easy_translate
repo_name: GitHub
edit_uri: edit/evalatuation/docs/

theme:
  name: material
  palette:
    scheme: default
    primary: amber
    accent: yellow
  language: en
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - search.highlight
    - content.code.annotate

nav:
  - Home: index.md
  - Evaluation:
    - Overview: overview.md
    - Metrics: metrics.md
    - Evaluator: evaluator.md
    - Models: model.md
    - Config: config.md
    - Usage: usage.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_root_full_path: false
            show_source: false

